apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
 name: tlssecret
spec:
 secretName: tlssecret
 dnsNames:
 - ingress.local
 acme:
   config:
   - http01:
       ingressClass: nginx
     domains:
     - ingress.local
 issuerRef:
   name: letsencrypt-prod
   kind: ClusterIssuer