---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .Values.ingress.name }}"
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingressClass }}"
    certmanager.k8s.io/cluster-issuer: "{{ .Values.certIssuer }}"
spec:
  tls:
  - hosts:
    - "micro.recipesavants.com"
    secretName: "tlssecret"
  rules:
  - host: "micro.recipesavants.com"
    http:
      paths:
      - path: /
        backend:
          serviceName: aks-helloworld-1-{{.Release.Name}}
          servicePort: 80
      - path: /hello2
        backend:
          serviceName: aks-helloworld-2-{{.Release.Name}}
          servicePort: 80
